
namespace BisleriumCafé.Data.Models
{
    // This class represents the data structure for Final PDF reporting data.
    public class ReportData
    {
        // Name of the item either Coffee or Add-Ins in the report.
        public string Name { get; set; }

        // Quantity of the item in the report.
        public int Quantity { get; set; }

        // Revenue generated by the item in the report.
        public double Revenue { get; set; }
    }
}
